import Image from 'next/image';
import Head from 'next/head';

import React, { useEffect } from 'react';
import axios from 'axios';
import { useRouter } from 'next/router';

import { NavBar, Stars, MovieDetails } from '../../../components';
import { useGlobalContext } from '../../../contexts/';

import { config, baseUrl } from '../../../services';

import { MovieData } from '../../../components/GenreRows';

export default function Detail() {
  const router = useRouter();
  const { id } = router.query;

  const { search, moviesList, setMoviesList } = useGlobalContext();

  // Get the movie to render from the moviesList
  const movieToRender = moviesList
    .filter((movie: MovieData) => movie.id === id)
    .pop();

  interface MovieDetails {
    year: string;
    runtime: string;
    director: string;
    cast: string[];
    rating: number;
    description: string;
    image: string;
    title: string;
  }

  const detailedMovie: MovieDetails = {
    year: '',
    runtime: '',
    director: '',
    cast: [],
    rating: 0,
    description: '',
    image: '',
    title: '',
  };

  if (movieToRender) {
    detailedMovie.title = movieToRender.title;
    detailedMovie.year = movieToRender.released_on.slice(0, 4);
    detailedMovie.runtime = movieToRender.length;
    detailedMovie.director = movieToRender.director;
    detailedMovie.cast = movieToRender.cast;
    detailedMovie.rating = movieToRender.imdb_rating / 2;
    detailedMovie.description = movieToRender.overview;
    detailedMovie.image = movieToRender.poster;
  }

  // Get all movies from the API
  const getAllMovies = async () => {
    const res = await axios.get(baseUrl, config());
    setMoviesList(res.data.movies);
  };

  useEffect(() => {
    getAllMovies();
  }, [search]);


  // If the movie to render is not found, render a loading message
  if (!movieToRender) {
    return <div>Loading...</div>;
  }

  return (
    <div className='container-fluid'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar />
      <div className='container pt-3 mt-5'>
        <div className='row'>
          <div className='col-5'>

            {/* Render the movie poster */}
            <Image
              alt='Next.js logo'
              src={detailedMovie.image}
              width={1200}
              height={400}
              style={{
                maxWidth: '100%',
                height: 'auto',
              }}
            />
          </div>
          <div className='col-7 fs-4'>
            <div className='row pb-4'>

              {/* Render the movie title and rating */}
              <div className='col-6'>{detailedMovie.title}</div>
              <div className='col-6'>

                {/* Render the movie rating */}
                <Stars rating={detailedMovie.rating} />
              </div>
            </div>
            <div className='row'>

              {/* Render the movie details */}
              <MovieDetails detailedMovie={detailedMovie} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
